steps:
  github-release:
    image: pcit/github-release
    settings:
      token: ${GITHUB_TOKEN}
      # repo: pcit-ce/release
      files:
        - Dockerfile
        - docker-entrypoint.sh
      overwrite: true
      draft: true
      prerelease: true
      note: nightly
      title: nightly
      target_commitish: refs/tags/nightly
